
const navData = {
    myAssignment: "My Assignment",
    chatWithMentor: "Chat with Mentor",
    profilename: "ProfileName",
};
  
export const referredData = {
    logo: "./src/assets/logo.png",
    uiUxReferEarnFriendsReferred: "UI/UX > Refer & Earn > Friends Referred",
    spanText1: "Friends who enrolled",
    spanText2: "(3)",
    dhirajSaxsena: "Dhiraj Saxsena",
    coursesEnrolled6: "Courses Enrolled(6)",
    address1: "14 Sep, 2022",
    uiUx1: "UI/UX",
    photoshop1: "Photoshop",
    illustrator1: "Illustrator",
    python1: "Python",
    place1: "MERN",
    java1: "Java",
    subhashMishra: "Subhash Mishra",
    coursesEnrolled231: "Courses Enrolled(23)",
    address2: "15 Sep, 2022",
    uiUx2: "UI/UX",
    python2: "Python",
    photoshop2: "Photoshop",
    illustrator2: "Illustrator",
    place2: "MERN",
    java2: "Java",
    c1: "C++",
    afterEffects1: "After Effects",
    reactNative1: "React Native",
    dsa1: "DSA",
    competitiveProgramming1: "Competitive Programming",
    dataScience1: "Data Science",
    premierePro1: "Premiere Pro",
    photography1: "Photography",
    singing1: "Singing",
    guitar1: "Guitar",
    digitalMarketing1: "Digital Marketing",
    financialModelling1: "Financial Modelling",
    webDevelopmentWithPhpSql1: "Web Development with PHP/SQL",
    appDevelopment1: "App Development",
    prafullKumar: "Prafull Kumar",
    coursesEnrolled232: "Courses Enrolled(23)",
    address3: "16 Sep, 2022",
    uiUx3: "UI/UX",
    python3: "Python",
    photoshop3: "Photoshop",
    illustrator3: "Illustrator",
    place3: "MERN",
    java3: "Java",
    c2: "C++",
    afterEffects2: "After Effects",
    reactNative2: "React Native",
    dsa2: "DSA",
    competitiveProgramming2: "Competitive Programming",
    dataScience2: "Data Science",
    premierePro2: "Premiere Pro",
    photography2: "Photography",
    singing2: "Singing",
    guitar2: "Guitar",
    digitalMarketing2: "Digital Marketing",
    financialModelling2: "Financial Modelling",
    webDevelopmentWithPhpSql2: "Web Development with PHP/SQL",
    appDevelopment2: "App Development",
    termsConditions: "Terms & Conditions",
    navProps: navData,
  };